// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/joke.ts";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/stories/button.tsx";
import * as $3 from "./routes/stories/index.tsx";
import * as $4 from "./routes/stories/sound-button.tsx";
import * as $5 from "./routes/stories/sound-group-button.tsx";
import * as $6 from "./routes/stories/sound-group.tsx";
import * as $7 from "./routes/stories/sound.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/LetterPractice.tsx";
import * as $$2 from "./islands/LettersExam.tsx";
import * as $$3 from "./islands/SoundAnswerButtonsStory.tsx";
import * as $$4 from "./islands/SoundGroupStory.tsx";
import * as $$5 from "./islands/SoundStory.tsx";
import * as $$6 from "./islands/WordAnswerButtonsStory.tsx";
import * as $$7 from "./islands/WordPractice.tsx";

const manifest = {
  routes: {
    "./routes/api/joke.ts": $0,
    "./routes/index.tsx": $1,
    "./routes/stories/button.tsx": $2,
    "./routes/stories/index.tsx": $3,
    "./routes/stories/sound-button.tsx": $4,
    "./routes/stories/sound-group-button.tsx": $5,
    "./routes/stories/sound-group.tsx": $6,
    "./routes/stories/sound.tsx": $7,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/LetterPractice.tsx": $$1,
    "./islands/LettersExam.tsx": $$2,
    "./islands/SoundAnswerButtonsStory.tsx": $$3,
    "./islands/SoundGroupStory.tsx": $$4,
    "./islands/SoundStory.tsx": $$5,
    "./islands/WordAnswerButtonsStory.tsx": $$6,
    "./islands/WordPractice.tsx": $$7,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
